include:
  #SonarQube e HuskyCI
  - project: "infradevops/pipelines/jobs"
    ref: main
    file: "tests/sonar-scanner.yml"
  # pipelines-count
  - project: "infradevops/pipelines-count"
    ref: master
    file: "jobs/notify-pubsub.yml"

stages:
  - .pre
  - test
  - export_env
  - package

pipelines-count:
  stage: .pre
  extends: .notify-pubsub
  only:
    - main
    - master
    
variables:
  MAJOR_VERSION: "8"

export_env:
  stage: export_env
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  script:
    - export DAY_OF_YEAR=$(date +%Y%m%d)
    - export MINOR="$DAY_OF_YEAR"
    - export VERSION_CORE="$MAJOR_VERSION.$MINOR.$CI_PIPELINE_ID"
    - export BUILD_VERSION="$VERSION_CORE"
    - export PRE_RELEASE_VERSION="$VERSION_CORE-dev"
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        export RELEASE_VERSION="$BUILD_VERSION"
      else
        export RELEASE_VERSION="$PRE_RELEASE_VERSION"
      fi
    - echo "RELEASE_VERSION=$RELEASE_VERSION" > release_info.env
    - echo "BUILD_VERSION=$BUILD_VERSION" >> release_info.env
    - echo "PRE_RELEASE_VERSION=$PRE_RELEASE_VERSION" >> release_info.env
  artifacts:
    reports:
      dotenv: release_info.env

package:
  image: docker-microsoft.$ARTIFACTORY_URL/dotnet/sdk:8.0
  stage: package
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  before_script:
    - |
      dotnet nuget add source https://$ARTIFACTORY_URL/artifactory/api/nuget/nuget-local \
        --name Artifactory \
        --username $ARTIFACTORY_USERNAME \
        --password $ARTIFACTORY_TOKEN \
        --store-password-in-clear-text
  script:
    - echo "Building version $RELEASE_VERSION"
    - mkdir /packages
    - dotnet pack ./nuget.csproj -p:Version=$RELEASE_VERSION -c Release -o packages
    - find packages/ -type f -name "*.nupkg" -exec dotnet nuget push {} --api-key $ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN -s Artifactory \;
  tags:
    - gcp-shared
  artifacts:
    paths:
      - packages/
    expire_in: 1 week
