name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MAJOR_VERSION: "8"

jobs:
  export_env:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
      build_version: ${{ steps.set_version.outputs.build_version }}
      pre_release_version: ${{ steps.set_version.outputs.pre_release_version }}

    steps:
      - name: Set version variables
        id: set_version
        run: |
          DAY_OF_YEAR=$(date +%Y%m%d)
          MINOR="$DAY_OF_YEAR"
          VERSION_CORE="$MAJOR_VERSION.$MINOR.${{ github.run_number }}"
          BUILD_VERSION="$VERSION_CORE"
          PRE_RELEASE_VERSION="$VERSION_CORE-dev"
          
          if [ "${{ github.ref_name }}" == "master" ]; then
            RELEASE_VERSION="$BUILD_VERSION"
          else
            RELEASE_VERSION="$PRE_RELEASE_VERSION"
          fi
          
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT
          echo "pre_release_version=$PRE_RELEASE_VERSION" >> $GITHUB_OUTPUT
          
          echo "Building version: $RELEASE_VERSION"

  package:
    runs-on: ubuntu-latest
    needs: export_env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and Pack
        run: |
          echo "Building version ${{ needs.export_env.outputs.release_version }}"
          mkdir -p packages
          dotnet pack ./nuget.csproj -p:Version=${{ needs.export_env.outputs.release_version }} -c Release -o packages

      - name: Publish to NuGet/Artifactory
        run: |
          find packages/ -type f -name "*.nupkg" -exec dotnet nuget push {} --api-key ${{ secrets.NUGET_API_KEY }} \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: packages/
          retention-days: 7